name: Deploy to dev.to
on:
  push:
    branches:
      - main

jobs:
  operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Publish articles on dev.to
        uses: sinedied/publish-devto@v1
        with:
          files: 'articles/**/*.md'
          devto_key: ${{ secrets.DEVTO_API_KEY }}
